language: cpp

# Ubuntu 14.04 Trusty support, for C++11 (clang at least)
sudo: required
dist: trusty

compiler:
    - clang
    - gcc

os:
    - linux
    - osx

before_script:
    - echo "$TRAVIS_OS_NAME"
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]];then wget http://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]];then sudo apt-get -f install libhfst45-dev libpugixml-dev; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];then wget http://apertium.projectjj.com/osx/install-nightly.sh -O - | sudo bash; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];then brew install pugixml; fi
    - ./autogen.sh
