language: cpp

# let linux be Ubuntu 14.04 Trusty
sudo: required
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - libstdc++-5-dev
    - clang
    - libpugixml-dev
    - libxml2-utils

matrix:
  include:
  - os: linux
    compiler: clang
    before_script:
    - wget http://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash
    - sudo apt-get -f install -y libhfst48-dev
    - ./autogen.sh

  - os: linux
    compiler: gcc
    # Trusty's default gcc doesn't have C++11; can't be in env since then travis overrides it:
    install:
    - CXX="g++-5" CC="gcc-5"
    before_script:
    - wget http://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash
    - sudo apt-get -f install -y libhfst48-dev
    - ./autogen.sh

  - os: osx
    compiler: clang
    # on osx, nightly goes in /usr/local
    env:
    - LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/local/lib" PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:/usr/local/share/pkgconfig:/usr/local/lib/pkgconfig" ACLOCAL_PATH="${ACLOCAL_PATH}:/usr/local/share/aclocal" PATH="${PATH}:/usr/local/bin"
    before_script:
    - wget http://apertium.projectjj.com/osx/install-nightly.sh -O - | sudo bash
    script:
    - scripts/get-pugixml-and-build

  - os: osx
    compiler: gcc
    # on osx, nightly goes in /usr/local
    env:
    - LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/local/lib" PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:/usr/local/share/pkgconfig:/usr/local/lib/pkgconfig" ACLOCAL_PATH="${ACLOCAL_PATH}:/usr/local/share/aclocal" PATH="${PATH}:/usr/local/bin"
    before_script:
    - wget http://apertium.projectjj.com/osx/install-nightly.sh -O - | sudo bash
    script:
    - scripts/get-pugixml-and-build
