language: cpp

# let linux be Ubuntu 14.04 Trusty
sudo: required
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - libstdc++-5-dev
    - clang
    - libpugixml-dev
    - libxml2-utils
    - libarchive-dev

matrix:
  include:
  - os: linux
    compiler: clang
    env:
    - VERBOSE=1
    before_script:
    - wget http://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash
    - sudo apt-get -f install -y libhfst49-dev libcg3-dev
    # - ./autogen.sh
    script:
    - scripts/travis-build

  - os: linux
    compiler: gcc
    # Trusty's default gcc doesn't have C++11; can't be in env since then travis overrides it:
    install:
    - CXX="g++-5" CC="gcc-5"
    env:
    - VERBOSE=1
    before_script:
    - wget http://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash
    - sudo apt-get -f install -y libhfst49-dev libcg3-dev
    # - ./autogen.sh
    script:
    - scripts/travis-build

  - os: osx
    compiler: clang
    # on osx, nightly goes in /usr/local
    env:
    - PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:/usr/local/share/pkgconfig:/usr/local/lib/pkgconfig" ACLOCAL_PATH="${ACLOCAL_PATH}:/usr/local/share/aclocal" PATH="${PATH}:/usr/local/bin"
    before_install:
    - travis_retry brew update
    - brew ls --versions pugixml    || travis_retry brew install pugixml
    - brew ls --versions libarchive || travis_retry brew install libarchive
    script:
    - scripts/travis-build

  - os: osx
    compiler: gcc
    # on osx, nightly goes in /usr/local
    env:
    - PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:/usr/local/share/pkgconfig:/usr/local/lib/pkgconfig" ACLOCAL_PATH="${ACLOCAL_PATH}:/usr/local/share/aclocal" PATH="${PATH}:/usr/local/bin"
    before_install:
    - travis_retry brew update
    - brew ls --versions pugixml    || travis_retry brew install pugixml
    - brew ls --versions libarchive || travis_retry brew install libarchive
    script:
    - scripts/travis-build

cache:
  directories:
    - $HOME/gtd-cache
    - $HOME/Library/Caches/Homebrew
