language: cpp

# let linux be Ubuntu 14.04 Trusty
sudo: required
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - libstdc++-5-dev
    - clang
    - libpugixml-dev
    - libxml2-utils
    - libarchive-dev
  coverity_scan:
    project:
      name: $TRAVIS_REPO_SLUG
      version: $TRAVIS_COMMIT
      description: "Build submitted via Travis CI"
    notification_email: unhammer+dill@mm.st
    build_command_prepend: "./autogen.sh && ./configure --enable-checker && make clean"
    build_command:   "make -j4"
    branch_pattern: coverity_scan

matrix:
  include:
  - os: linux
    compiler: clang
    env:
    - VERBOSE=1
    before_install:
    - if [[ $TRAVIS_BRANCH = coverity_scan ]]; then echo "Running coverity_scan on this configuration …"; echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt; fi
    before_script:
    - wget http://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash
    - sudo apt-get -f install -y libhfst-dev libcg3-dev
    # - ./autogen.sh
    script:
    - scripts/travis-build

  - os: linux
    compiler: gcc
    # Trusty's default gcc doesn't have C++11; can't be in env since then travis overrides it:
    install:
    - CXX="g++-5" CC="gcc-5"
    env:
    - VERBOSE=1
    before_install:
    - if [[ $TRAVIS_BRANCH = coverity_scan ]]; then echo "We only coverity_scan for one square of the matrix, exiting"; exit 0; fi
    before_script:
    - wget http://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash
    - sudo apt-get -f install -y libhfst-dev libcg3-dev
    # - ./autogen.sh
    script:
    - scripts/travis-build

  - os: osx
    compiler: clang
    install:
    - COMPILER="gcc"
    # on osx, nightly goes in /usr/local
    env:
    - PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:/usr/local/share/pkgconfig:/usr/local/lib/pkgconfig" ACLOCAL_PATH="${ACLOCAL_PATH}:/usr/local/share/aclocal" PATH="${PATH}:/usr/local/bin"
    before_install:
    - if [[ $TRAVIS_BRANCH = coverity_scan ]]; then echo "We only coverity_scan for one square of the matrix, exiting"; exit 0; fi
    - travis_retry brew update
    - brew ls --versions pugixml    || travis_retry brew install pugixml
    - brew ls --versions libarchive || travis_retry brew install libarchive
    script:
    - scripts/travis-build

  - os: osx
    compiler: gcc
    # on osx, nightly goes in /usr/local
    env:
    - PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:/usr/local/share/pkgconfig:/usr/local/lib/pkgconfig" ACLOCAL_PATH="${ACLOCAL_PATH}:/usr/local/share/aclocal" PATH="${PATH}:/usr/local/bin"
    before_install:
    - if [[ $TRAVIS_BRANCH = coverity_scan ]]; then echo "We only coverity_scan for one square of the matrix, exiting"; exit 0; fi
    - travis_retry brew update
    - brew ls --versions pugixml    || travis_retry brew install pugixml
    - brew ls --versions libarchive || travis_retry brew install libarchive
    script:
    - scripts/travis-build

cache:
  directories:
    - $HOME/gtd-cache
    - $HOME/Library/Caches/Homebrew

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "2lUcvNAdm5QO5m2r9eZQ6TAD8qiU8S0DzntXLUBPFtWmjD6atuptMr+6mVfgjG67eIfr05Q3v9jTpkb7JzSdqeB+foju6m/9iBtDXFRHfaED3OenWrI4ovFCRy+ClbT7rfHlwUYz/DKEAK8JEcDbqMG9hO4R9BTiPGJ7I0VuQxSeuSpVsxO+2CMqmEoLhtSs7+T929kn/fvVpvmHxYpmqswU1Hbjkb0SEYqmHlrNRWn/dFhYsm9EtRoBMX2NSC5MPGg+kadGZQQdhQJx8iODes+rVsLJs2sRVIcRy8te3R0Dn5FkCZUap+ntsGa1aGQufgaUCf4gwbGMAK0Ad6Wsyf/iuZmplKzr5U5MY4JI7Tmk0SzqndHYX9xL2CdtoHDxllK3UpgqNgUspkBdIwVdEol9jT2AtSngsl9MF5Z/u/yYgTaUyEEF8hNq7JLZR/EsrMcBhWi/ClV/7T2657h31AzMzP3eUxOW8XmX0Y25g/xicMvtGeE0t7ArGmCqFpM/417E3tmhZ2D/hInsprGetSwCuU7NJUhqPo61/+EnQ3njTFV4ooqwIS+93cx42yiueAldjgeAebpmKSxkbcO8Ayj5sVAAJQTCthDiCFVYvL3AT/VdS1NAB1HbLyku/tCxOmdKIlO5+MZqKlfr2nb0G57CLTt/3ac6Hb2WmgmgUNI="
